.rules_master:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

.rules_master_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
  allow_failure: true

.rules_development:
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: on_success

.rules_development_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: manual
  allow_failure: true

.rules_staging:
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: on_success

.rules_staging_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
  allow_failure: true

.rules_production:
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: on_success

.rules_production_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: manual
  allow_failure: true