name: Run zammad container on staging environment

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Docker compose command'
        required: true
        default: 'up -d'
        type: choice
        options:
        - up -d
        - down
        - restart

jobs:
  run_container: 
    name: run the container in docker on dev servers
    runs-on:
      - mbaza-product-test
    steps:
      - name: import secrets 
        id: secrets
        uses: hashicorp/vault-action@v2.4.3
        with:
          url: https://vault.dev.mbaza.org
          method: github
          githubToken: ${{ secrets.MBAZA_GITHUB_TOKEN }}
          secrets: |
              mbaza/zammad/dev ZAMMAD_HOST;
              mbaza/zammad/dev ZAMMAD_USER;
              mbaza/zammad/dev ZAMMAD_PASS;
      - name: run up the container
        run: |-
          cd /home/mbaza-test/mbaza/zammad/current/zammad-docker
          envsubst < .env.example > .env
          docker compose ${{github.event.inputs.COMMAND}}
