name: Maintain service on dev

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Choose between restart,backup and restore service'
        required: true
        default: 'RESTART'
        type: choice
        options:
        - RESTART
        - BACKUP
        - RESTORE

jobs:
  run_zammad_container: 
    uses: mbaza-product/infratructure.github.template/.github/workflows/maintain.yaml@main
    with: 
      PROJECT_ROOT_PATH: /home/mbaza-dev/mbaza/zammad
      ENVIRONMENT: zammad
      PARAMETER: ${{ github.event.inputs.command }}
      SERVICE: zammad
      PROJECT_BACKUP_PATH: /home/mbaza-dev/mbaza/backup
      SERVICE_LOCATION_PATH: zammad-docker
      BACKUP_SCRIPT_FILE: shellscripts/backup-multiple-volumes.sh
      RESTORE_SCRIPT_FILE: shellscripts/restore-volume.sh
